### PR TITLE
search: add connected component finding function

### PR DESCRIPTION
**Pull request by kortschak**
I will clean up the use of the example graph in another PR.

### CODE REVIEW

**Comment by kortschak** [comment]
@soniakeys @Jragonmiris

**Comment by Jragonmiris** [comment]
If we do this, we should probably remove Tarjan due to redundancy.

**Comment by kortschak** [comment]
They do different things. Tarjan returns SCCs from directed graphs, ConnectedComponents returns CCs from undirected graphs (accepting, but removing edge directions if the graph is directed).

**Comment by kortschak** [comment]
I've had a change of idea here. I have moved the general case into traverse and kept search.ConnectedComponents as a simple wrapper around WalkAll.

I'm still thinking about this so it may change a little.

**Comment by soniakeys** [comment]
Very nice use of traverse.

**Comment by kortschak** [comment]
@jragonmiris I forgot we allow tarjan to operate on undirected graphs. I can drop support for those. Then we have no redundancy and direct people to the appropriate function. Is that OK with you?

**Comment by Jragonmiris** [comment]
That works. I think we may need an undirected/directed redesign anyway.
There are a silly amount of problems with it as of now.

**Comment by kortschak** [comment]
Yes, I agree. I was thinking of posting a design reassessment mail to gonum-dev over the next week or so.

I've made minor changes including the removal of Tarjan handling of undirected graphs. I'll squash when this is accepted and merge, then send another PR which will clean up some of the mess I've made spreading things around (start of internal and factoring other things that are repetitive)

PTAL

**Comment by kortschak** [comment]
ping

**Comment by Jragonmiris** [comment]
Works for me, though resolving this with the Atomize branch is going to get real silly real quick. (That doesn't mean don't merge, just an observation :p )

**Comment by kortschak** [comment]
That's why I want it merged now.

I am going to have a look at the atomize branch, but there is a lot of movement there. The review is going to be very difficult. I think that it might be worth using it as exploration and making smaller, more directed changes based on what we learn there. I'll address this more on that PR.

**Pull request merged**
