### PR TITLE
search: add vertex ordering function

### PR DESCRIPTION
**Pull request by kortschak**

### CODE REVIEW

**Comment by kortschak** [comment]
@soniakeys Please take a look.

I'm thinking it might be work adding a return value that is [][]graph.Node sliced from the order value but is each of the cores. This is almost no extra work, but potentially useful.

**Comment by soniakeys** [comment]
This looks very cool.  I agree that returning the slice sliced by order would be good.  A slightly more economical alternative would be just a slice of integer positions where the nodes could be sliced.  But a slice of slices sounds more convenient.

**Comment by kortschak** [comment]
PTAL

**Comment by soniakeys** [comment]
LGTM  :)

**Pull request merged**
