### PR TITLE
search: remove BreadthFirstSearch and DepthFirstSearch

### PR DESCRIPTION
**Pull request by kortschak**
@gonum/developers PTAL

### CODE REVIEW

**Comment by vladimir-ch** [comment]
Can you just give a short motivation for doing this?

**Comment by Jragonmiris** [comment]
I agree with BFS since it's just an A* wrapper, but why DFS?

**Comment by kortschak** [comment]
@vladimir-ch the motivation is in the commit message.

@Jragonmiris You can get DFS from traverse.DepthFirst. I think that this DFS is misleading because it returns a path. As I say in the commit message, this path is almost always going to be not what the client wanted.

**Comment by vladimir-ch** [comment]
Ah, sorry, should have looked there first. The DFS code was not perfect anyway, just nitpicking, but the first closedSet.Has() check was unnecessary. LGTM

**Pull request merged**
