### PR TITLE
path: fix documentation for function DijkstraFrom

### PR DESCRIPTION
**Pull request by juroland**
This commit changes complexity based on the reference provided in comments (i.e. http://www.cs.utexas.edu/ftp/techreports/tr07-54.pdf). The previously announced complexity could be reached by using a fibonacci heap and its decrease key operation.

### CODE REVIEW

**Comment by kortschak** [comment]
I'm trying to figure out where you get this from. The paper gives the time for DIJKSTRA-NODEC in table 3 as "O(m+(n+D)·log(n+D))" where D is the decrease-key operations. Since D ≤ m this becomes for our purposes "O(m + n·log(n))" which is what we currently have.

**Comment by juroland** [comment]
This table seems to give the I/O complexity. The time complexity is decribed in section B.2.

**Comment by kortschak** [comment]
Ah yes, sorry.

**Comment by kortschak** [comment]
Thank you.

**Pull request merged**
