### PR TITLE
topo: Add union-find version of connectedComponents

### PR DESCRIPTION
**Pull request by tcharding**
Issue #179 suggests replacing connectedComponents() with union-find
version would increase run time efficiency. This patch implements
the union-find version, however benchmarking as implemented does not
show any speed increase. This patch is not a merge candidate but is
intended for discussion purposes only.

### CODE REVIEW

**Comment by tcharding** [comment]
Is this implementation what you had in mind when opening this issue? I think that the benchmarking is not giving a clear picture since it runs connectedComponents many times on a small graph run time is dominated by map creation. Would benchmarking it against a large graph be more appropriate?

**Comment by kortschak** [comment]
Yes, that's pretty much it. Note that you can use path compression which theoretically should improve performance for large n (I have not found this to be true for implementations in Go). It may be worth benchmarking for a set of graph sizes to find where/if there is an improvement.

**Comment by tcharding** [comment]
Implemented path compression. Created set of graphs in topo/bench_test.go. Running benchmarks over the set seems to imply that the union find implementation is slower. The germane output (re-ordered for convenience) was;
```
BenchmarkConnectedComponents_10-4    	  200000	     10389 ns/op
BenchmarkConnectedComponentsUF_10-4  	  100000	     17103 ns/op

BenchmarkConnectedComponents_100-4   	    2000	    715846 ns/op
BenchmarkConnectedComponentsUF_100-4 	    2000	   1267222 ns/op

BenchmarkConnectedComponents_1000-4  	      20	  79112920 ns/op
BenchmarkConnectedComponentsUF_1000-4	      10	 116054424 ns/op
```

**Comment by tcharding** [comment]
Re-implemented path compression to compress complete tree instead of just the leaf node found during 'find'. Did not improve benchmarks.

**Comment by kortschak** [comment]
Yeah, I'm not surprised. How about using a for loop - the recursion is necessarily linear, so that should be more efficient. I doubt it will be a win though.

**Comment by kortschak** [comment]
Have you done any profiling on this to see where we are spending the time?

**Comment by tcharding** [comment]
Here is the profile output for ConnectedComponentsUF_1000 benchmark (`bench_test.go`).
```
1610ms of 1870ms total (86.10%)
Showing top 10 nodes out of 59 (cum >= 140ms)
      flat  flat%   sum%        cum   cum%
     350ms 18.72% 18.72%      420ms 22.46%  runtime.mapaccess2_fast64
     240ms 12.83% 31.55%      280ms 14.97%  runtime.mapaccess1_fast64
     220ms 11.76% 43.32%      440ms 23.53%  runtime.scanobject
     190ms 10.16% 53.48%      190ms 10.16%  runtime.mapiternext
     150ms  8.02% 61.50%      150ms  8.02%  github.com/gonum/graph/topo.find
     110ms  5.88% 67.38%      110ms  5.88%  runtime.aeshash64
     100ms  5.35% 72.73%      760ms 40.64%  github.com/gonum/graph/topo.(*disjointSet).find
      90ms  4.81% 77.54%      580ms 31.02%  github.com/gonum/graph/simple.(*UndirectedGraph).From
      80ms  4.28% 81.82%       80ms  4.28%  github.com/gonum/graph/topo.pathCompress
      80ms  4.28% 86.10%      140ms  7.49%  runtime.greyobject

```

I have come up against these sort of profiles before and have always dealt with it by removing the map and using a slice instead. I cannot see a way to do this here because we support nodes with arbitrary ID's.

For your information my analysis of the two algorithms `union-find` (UF) and original `depth first search` (DSF) is as follows, please correct me if I am wrong. Let N be number of nodes and M be number of edges.

DSF is straight from the literature _O(N + M)_. [Sedgewick 98]

UF is a little more involved. 

1. Add all nodes to disjoint set _O(N)_
2. Process edges _O(M Log N)_  [Sedgewick 98]
3. Get connected components from disjoint set _O(N)_

So for sparse graphs UF is dominated by node count, therefore _O(N)_ and for dense graphs UF is dominated by edge processing _O(M Log N)_

Clearly _O(N)_ can never outperform _O(N + M)_ . Can _O(M Log N)_ outperform _O(N + M)_? I don't know the math to work that out, but I am guessing it can else why does the literature suggest union-find in the first place for this problem.

**Comment by kortschak** [comment]
>Clearly *O(N)* can never outperform *O(N + M)*

Reverse this? *O(n)* < *O(n+m)* for all m > 0.

The time for union-find clustering is AFAIU *O(m [log\*](https://en.wikipedia.org/wiki/Iterated_logarithm) n)*. which for all intents and purposes is ~*O(m)* for values that we can represent.

[This](https://www.wolframalpha.com/input/?i=plot++m*log*+n+%3C+m+%2B+n+for+n%3D1..1e12+and+m%3D1..1e12) is what wolfram alpha thinks.

So it looks like for sparse graphs, the union-find wins, but the the majority of cases, the simple depth first search wins (the winning domain [shrinks for *O(mlogn)* implementations](https://www.wolframalpha.com/input/?i=plot++m*log+n+%3C+m+%2B+n+for+n%3D1..1e12+and+m%3D1..1e12)).

**Comment by tcharding** [comment]
So does this mean we should have both implementations so the client has a choice depending on their use case? If so, shall I clean up the union-find implementation, add comments stating what we have learned and submit a PR?

**Comment by kortschak** [comment]
From the fraction of the plot that shows benefit and the high constants from map look up, I think this means that this was informative, but falling on the side of not including it. If someone comes up with a better way of doing the sparse look up, then that may change, but all up, I think this is not worth going forward with.

I really want to thank you for doing all this though, it provides actual support for the current approach. I'll leave the final decision up to you to whether you want to try to push it further.

**Comment by tcharding** [comment]
Happy to close it as you say. It has most definitely been informative.

**Pull request closed without merging**
